deploy:
  hosts:
    local:
      ansible_connection: local
      ansible_host: localhost

# registry:
#   hosts:
#     registry:
#       ansible_host: 10.100.0.11
#   vars:
#     ansible_ssh_user: vagrant
#     ansible_ssh_pass: vagrant

registry:
  children:
    deploy:

consul:
  hosts:
    consul01:
      ansible_host: 10.100.0.11
    consul02:
      ansible_host: 10.100.0.12
    consul03:
      ansible_host: 10.100.0.13
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant

vagrant:
  hosts:
    node01:
      ansible_host: 10.100.0.11
    node02:
      ansible_host: 10.100.0.12
    node03:
      ansible_host: 10.100.0.13
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
    box_user: user
    box_pass: qwe123
    cpu: 1
    ram: 2048
    cidr: 10.100.0.0/24
