config_dir: "{{ jenkins_config_dir | default(compose_dir) }}"
data_dir: "{{ jenkins_data_dir | default(compose_dir) }}"
version: "{{ jenkins_version | default('2.138.3') }}"
stack_name: "{{ jenkins_stack_name | default('jenkins') }}"

jenkins_admin_pass: "admin"
jenkins_admin_user: "admin"
jenkins_data_vol: "jenkins-data"

directories:
  - "{{ compose_dir }}"
  - "{{ config_dir }}"
  - "{{ data_dir }}"

templates:
  - { file: "config.yml", dest: "{{ config_dir }}" }

volumes:
  - "{{ jenkins_data_vol }}"

images:
  - name: "jenkins-master"
    prefix: "odavid/my-bloody-jenkins"
    tag: "{{ version }}"
    dns: "{{ dns_server }}"
    ports:
      - '8081:8080'
      - '50000:50000'
    environment:
      - SERVICE_50000_NAME=slaves
      - "SERVICE_8081_NAME=jenkins"
      - "SERVICE_8081_TAGS=jenkins"
      - SERVICE_50000_TAGS="jenkins"
      - SERVICE_NAME=jenkins
      - JAVA_OPTS_MEM='-Xmx1g'
      # Disable hyper provision of slaves - docker plugin strategy is enough
      - JAVA_OPTS_LOAD_STATS_CLOCK=''
      - JENKINS_ENV_ADMIN_USER="{{ jenkins_admin_user }}"
      - JENKINS_ENV_HOST_IP="{{ hostvars[inventory_hostname]['ansible_host'] }}"
      - JENKINS_ENV_CONFIG_YML_URL=file:///config.yml
      - JENKINS_ENV_QUIET_STARTUP_PERIOD=120
      - JENKINS_ADMIN_PASSWORD="{{ jenkins_admin_pass }}"
    # TODO FIXME No page found on plugin installs
    #  - JENKINS_ENV_PLUGINS="badge,ghprb,nodelabelparameter,script-security"
    volumes:
      - "{{ config_dir }}/config.yml:/config.yml"
      - "{{ jenkins_data_vol }}:/var/jenkins_home"
      #- "{{ config_dir }}/jenkins-workspace-home:/jenkins-workspace-home"
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - "{{ docker_swarm_overlay.name }}"
    deploy:
      endpoint_mode: vip
      replicas: 1 # FIXME cant get int
      mode: replicated
      placement:
        constraints: [node.role ==  worker]
      labels:
        - "traefik.frontend.rule=Host:jenkins.service.{{ domain_name }}"
        - traefik.enable=true
        - "traefik.port=8080"
        - traefik.tags=jenkins
        - traefik.docker.network=swarm_network
        - traefik.redirectorservice.frontend.entryPoints=http
        # - com.df.port=8080
        # - com.df.notify=true
        # - com.df.distribute=true
        # - com.df.shortName=true
        # - com.df.servicePath=/login
        # - com.df.serviceName='jenkins-master'
        # - com.df.reqPathSearch='/p/'
        # - com.df.reqPathReplace='/'
