---
- name: "Check if registry on deployer"
  set_fact:
    registry_ip: "{{ hostvars[groups['registry'][0]]['ansible_default_ipv4']['address'] }}"
  when:
  - "'localhost' in hostvars[groups['registry'][0]]['ansible_host']"

- name: "Check if registry on remote"
  set_fact:
    registry_ip: "{{ hostvars[groups['registry'][0]]['ansible_host'] }}"
  when:
  - "'localhost' not in hostvars[groups['registry'][0]]['ansible_host']"

- debug:
    msg: "{{ registry_ip }}"

- name: "Configure | Create compose dir -> {{ compose_dir }}"
  become: True
  file:
    path: "{{ compose_dir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: "Configure | Deploy compose files"
  vars:
    registry_ip: "{{ registry_ip }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ compose_dir }}/{{ item }}"
    lstrip_blocks: true
  with_items:
  - docker-compose.yml
  tags:
  - compose
