---
- name: "--> Archive"
  vars:
    registry_role: true # TODO FIXME role_path | basename not interable
  run_once: true
  include_tasks: "archive-images.yml"
  with_items:
  - "{{ images }}"
  loop_control:
    loop_var: image

- name: "--> Config"
  include_tasks: ./configure_nodes.yml

- name: "--> Run"
  import_tasks: ./run.yml
  run_once: true
