---
- name: "Archive | Archive docker images to deployer"
  run_once: true
  include_tasks: "archive-images.yml"
  with_items:
  - "{{ images }}"
  loop_control:
    loop_var: image

- name: "Archive docker image"
  include_tasks: "{{ role_path }}/../archive_binary/tasks/docker-archive.yml"
  with_items:
  - "{{ images }}"
  loop_control:
    loop_var: image

- name: "Create compose dir -> {{ compose_dir }}"
  become: true
  file:
    path: "{{ compose_dir }}"
    state: directory
    owner: "{{ ansible_user }}"

- name: "Deploy compose files"
  template:
    src: "{{ item }}.j2"
    dest: "{{ compose_dir }}/{{ item }}"
    lstrip_blocks: true
  with_items:
  - docker-compose.yml
  tags:
  - compose

- name: "Stop containers"
  docker_service:
    project_src: "{{ compose_dir }}"
    state: absent
  ignore_errors: true
  register: compose
  when: purge

- name: "Start containers"
  become: true
  docker_service:
    project_src: "{{ compose_dir }}"
    remove_orphans: true
    state: present
    restarted: true
  register: compose
