- name: "Configure | Create {{ stack_name }} dirs"
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"

- name: "Configure | Deploy {{ stack_name }} config"
  template:
    lstrip_blocks: true
    src: "{{ item }}.j2"
    dest: "{{ config_dir }}/{{ item }}"
  with_items:
   - server-config.json
   - client-config.json
