---
- hostname: swarm-worker-01
  box_name: yk0/ubuntu-xenial
  box_user: user
  box_pass: qwe123
  cpu: 1
  ram: 2048
  cidr: 10.100.0.0/24
  ip: 10.100.0.21
  os: yk0

- hostname: swarm-manager-01
  box_name: yk0/ubuntu-xenial
  box_user: user
  box_pass: qwe123
  cpu: 1
  ram: 2048
  cidr: 10.100.0.0/24
  ip: 10.100.0.11
  os: yk0

- hostname: swarm-manager-02
  box_name: yk0/ubuntu-xenial
  box_user: user
  box_pass: qwe123
  cpu: 1
  ram: 2048
  cidr: 10.100.0.0/24
  ip: 10.100.0.12
  os: yk0

- hostname: swarm-manager-03
  box_name: yk0/ubuntu-xenial
  box_user: user
  box_pass: qwe123
  cpu: 1
  ram: 2048
  cidr: 10.100.0.0/24
  ip: 10.100.0.13
  os: yk0

  #- hostname: ubu01
  #  box_name: yk0/ubuntu-xenial
  #  box_user: user
  #  box_pass: qwe123
  #  cpu: 1
  #  ram: 2048
  #  cidr: 10.100.0.0/24
  #  ip: 10.100.0.21
  #  os: yk0
  #- hostname: ubu02
  #  box_name: yk0/ubuntu-xenial
  #  box_user: user
  #  box_pass: qwe123
  #  cpu: 1
  #  ram: 2048
  #  cidr: 10.100.0.0/24
  #  ip: 10.100.0.21
  #  os: yk0
  #- hostname: ubu03
  #  box_name: yk0/ubuntu-xenial
  #  box_user: user
  #  box_pass: qwe123
  #  cpu: 1
  #  ram: 2048
  #  cidr: 10.100.0.0/24
  #  ip: 10.100.0.21
  #  os: yk0
  #- hostname: deployer
  #  box_name: yk0/ubuntu-xenial
  #  box_user: user
  #  box_pass: qwe123
  #  cpu: 1
  #  ram: 2048
  #  cidr: 10.100.0.0/24
  #  ip: 10.100.0.21
  #  os: yk0

