---
- debug: var=internet_available

- debug:
    msg: "No hostname resolvation detected, Please check your DNS."
  when: "internet_available == ''"


- block:
  - name: "Download external binaries"
    get_url:
      url: "{{ item.url }}"
      dest: "{{ reqs_dir }}/{{ item.name }}"
      sha256sum: "{{ item.sha256 }}"
      validate_certs: no
    with_items:
    - "{{ binaries }}"
    when:
    - binaries is defined

  - name: "Install pip2pi"
    pip:
      name: "pip2pi"
      state: latest

  - name: "Archive pip packages"
    shell: 'pip2pi {{ pypi_dir }} {{ item }}'
    with_items:
      - "{{ python_packages }}"

  when: internet_available | bool
