deploy:
  hosts:
    local:
      ansible_connection: local
      ansible_host: localhost

# registry:
#   hosts:
#     registry:
#       ansible_host: 10.100.0.11
#   vars:
#     ansible_ssh_user: vagrant
#     ansible_ssh_pass: vagrant

registry:
  children:
    deploy:

consul:
  children:
    vagrant:

# swarm-cluster:
#   children:
#     swarm-managers:
#     swarm-workers:

# swarm-init-master:
#   children:
#     vagrant:
#       hosts:
#         swarm-manager-01

# swarm-managers:
#   children:
#     vagrant:
#       hosts:
#         swarm-manager-[01:03]

swarm-workers:
  children:
    vagrant:
      # hosts:
      #   swarm-worker-01

vagrant:
  hosts:
    swarm-manager-01:
      ansible_host: 10.100.0.11
    swarm-manager-02:
      ansible_host: 10.100.0.12
    swarm-manager-03:
      ansible_host: 10.100.0.13
    swarm-worker-01:
      ansible_host: 10.100.0.21
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
    box_user: user
    box_pass: qwe123
    cpu: 1
    ram: 2048
    cidr: 10.100.0.0/24
