---
- name: "Network advanced settings"
  sysctl: name="{{ item.key }}" value="{{ item.value }}"
  with_items:
  - { key: "net.ipv4.ip_forward", value: 1 }
  - { key: "net.ipv4.conf.all.rp_filter", value: 0 }
  - { key: "net.ipv4.conf.default.rp_filter", value: 0 }

#- name: "Install packages"
#  package:
#    name: "{{ item }}"
#    state: installed
#  with_items:
#  - virtualbox
#  - vagrant
#  - xorg
#  - xauth

- name: "create vagrant directory"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ vagrant_dir }}"
  - "{{ logs_dir }}"

- name: "Deploy Vagrant configuration"
  template:
    src: "{{ item }}.j2"
    dest: "{{ vagrant_dir }}/{{ item }}"
  with_items:
  - Vagrantfile
  - vagrant.yml
  - bootstrap-ubuntu.sh

- name: "Destroy previous machines"
  shell:
    "{{ item }}"
  args:
    chdir: "{{ vagrant_dir }}"
  ignore_errors: true
  with_items:
  - "vagrant destroy --force"
  - "rm -rf .vagrant/machines/*"
  - "for pid in $(ps -ef | grep VBoxHeadless | grep -v grep | awk '{print $2}'); do kill -15 $pid; done;"
  - "rm -f *vdi"

- name: "Instantiate virtual machines"
  shell:
    "vagrant up {{ item }}" # >> {{ logs_dir }}/vagrant.log 2>&1
  args:
    chdir: "{{ vagrant_dir }}"
  with_items:
  - "{{ groups['virt-nodes'] }}"

