FROM {{ registry_hostname }}/{{ item.1.build.from }}

COPY sources.list /etc/apt/sources.list
COPY backup-repo.sh /

RUN apt update && apt install -y python3-dev python3-pip
RUN pip3 install awscli

USER root
RUN chmod +x /backup-repo.sh

ENTRYPOINT ["/backup-repo.sh"]
