---
- name: "--> Archive"
  run_once: true
  include_tasks: "archive-images.yml"
  with_items:
  - "{{ images }}"
  loop_control:
    loop_var: image

- name: "--> Config"
  include_tasks: ./configure_nodes.yml

- name: "--> Run"
  run_once: true
  delegate_to: "{{ swarm_master }}"
  import_tasks: ./run.yml
