---
- name: "Archive | Archive docker images to deployer"
  run_once: true
  include_tasks: "archive-images.yml"
  with_items:
  - "{{ images }}"
  loop_control:
    loop_var: image

- name: "Archive | Fetch docker images"
  include_tasks: "{{ role_path }}/../archive_binary/tasks/docker-archive.yml"
  with_items:
  - "{{ images }}"
  loop_control:
    loop_var: image

- include_tasks: ./configure_nodes.yml

- delegate_to: "{{ swarm_master }}"
  import_tasks: ./run.yml
  run_once: true
