- name: "Install common packages"
  become: true
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ common_packages }}"
  when: "'apt' in ansible_pkg_mgr"

- name: "Install Docker"
  include_tasks: ./docker-install.yml
  static: no
  when: "'apt' in ansible_pkg_mgr"

- debug:
    msg: "{{ registry_hostname }}"

- name: "REGISTRY on DEPLOYER"
  set_fact:
    registry_ip: "{{ hostvars[groups['registry'][0]]['ansible_default_ipv4']['address'] }}"
  when:
  - "'localhost' in hostvars[groups['registry'][0]]['ansible_host']"

- name: "REGISTRY on REMOTE"
  set_fact:
    registry_ip: "{{ hostvars[groups['registry'][0]]['ansible_host'] }}"
  when:
  - "'localhost' not in hostvars[groups['registry'][0]]['ansible_host']"

- name: "Purge old lines"
  lineinfile:
    path: /etc/hosts
    regex: "registry"
    state: absent
  when: edit_hosts | bool

- name: "Configure Registry DNS"
  lineinfile:
    path: /etc/hosts
    line: "{{ registry_ip }}  {{ registry_host }}"
  when: edit_hosts | bool
