---
- hosts: '{{ target_hosts | d("deploy") }}'
  tasks:
  - setup:

- hosts: '{{ target_hosts | d("deploy") }}'
  gather_facts: yes
  become: yes
  tasks:
  - include_role:
      name: archive_binary
    when: internet_available | bool

- hosts: '{{ target_hosts | d("all") }}'
  gather_facts: yes
  become: yes
  roles:
    - { role: common }
