---
- hosts: all:!deploy
  tasks:
      - name: "Deploy public key"
        authorized_key:
            state: present
            user: "{{ ansible_ssh_user }}"
            key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
