---
- hosts: '{{ target_hosts | d("all") }}'
  become: true
  roles:
      - { role: common }

- hosts: '{{ target_hosts | d("registry") }}'
  become: true
  roles:
      - { role: registry, purge: false }
