---
- hosts: consul-master
  become: true
  tasks:
      - name: "Purge previous containers"
        shell: "docker ps -a -q | xargs docker rm -f || /bin/true"

      - name: "Run consul master"
        docker_container:
          name: consul
          image: consul
          env:
              # CONSUL_ALLOW_PRIVILEGED_PORTS: ""
            CONSUL_HTTP_ADDR: "{{ hostvars[inventory_hostname]['ansible_host'] }}:8500"
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
          command: "agent -server -bind={{ hostvars[inventory_hostname]['ansible_host'] }} -retry-join={{ hostvars[groups['consul-master'][0]]['ansible_host'] }} -bootstrap-expect=1 -client={{ hostvars[inventory_hostname]['ansible_host'] }} -ui"
          network_mode: host
          state: started
          recreate: yes
        when: inventory_hostname in groups['consul-master'][0]
        

      - name: "sleep"
        shell: sleep 5

      - name: "Run consul join"
        docker_container:
          name: consul
          image: consul
          env:
              #CONSUL_ALLOW_PRIVILEGED_PORTS: ""
            CONSUL_HTTP_ADDR: "{{ hostvars[inventory_hostname]['ansible_host'] }}:8500"
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
          command: "agent -server -bind={{ hostvars[inventory_hostname]['ansible_host'] }} -join={{ hostvars[groups['consul-master'][0]]['ansible_host'] }} -client={{ hostvars[inventory_hostname]['ansible_host'] }} -ui"
          network_mode: host
          state: started
          recreate: yes
        when: inventory_hostname not in groups['consul-master'][0]

      - name: "sleep"
        shell: docker ps -a && docker logs consul
        register: bb

      - debug:
          var: bb.stdout
