---
- hosts: deploy
  vars:
    collect:
        - "swarm-manager"
        - "swarm-manager-dev"
    dict_test: [{'name': 'swarm-manager'},{'name': 'swarm'}]
  tasks:
    - debug:
        msg: "{{ item.name }}"
      with_items: "{{ dict_test }}"
      loop_control:
          label: "{{ item.name }}"
      when:  item.name in collect

